# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: "3.7"

volumes:
  peer40.org1.example.com:

networks:
  test:
    name: fabric_test

services:
  peer40.org1.example.com:
    container_name: peer40.org1.example.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer40.org1.example.com
      - CORE_PEER_ADDRESS=peer40.org1.example.com:5851
      - CORE_PEER_LISTENADDRESS=0.0.0.0:5851
      - CORE_PEER_CHAINCODEADDRESS=peer40.org1.example.com:5852
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:5852
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer40.org1.example.com:5851
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer40.org1.example.com:5851
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:15851
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../organizations/peerOrganizations/org1.example.com/peers/peer40.org1.example.com/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/org1.example.com/peers/peer40.org1.example.com/tls:/etc/hyperledger/fabric/tls
      - peer40.org1.example.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 5851:5851
      - 15851:15851
    networks:
      - test
